language: php

php:
  - 5.6
  - 7.1
  - nightly

before_script:
  - composer install

script:
  - composer test:coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
